Collections:
- Metadata:
    Architecture: []
  Name: README
  Paper:
  - https://openaccess.thecvf.com/content_CVPR_2019/html/Karras_A_Style-Based_Generator_Architecture_for_Generative_Adversarial_Networks_CVPR_2019_paper.html
  README: configs/styleganv1/README.md
Models:
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/styleganv1/styleganv1_ffhq_256_g8_25Mimg.py
  In Collection: README
  Metadata:
    Training Data: FFHQ
  Name: styleganv1_256
  Results:
  - Dataset: FFHQ
    Metrics:
      FID50k: 6.09
      P&R50k_full: 70.228/27.050
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/styleganv1/styleganv1_ffhq_256_g8_25Mimg_20210407_161748-0094da86.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/styleganv1/styleganv1_ffhq_1024_g8_25Mimg.py
  In Collection: README
  Metadata:
    Training Data: FFHQ
  Name: styleganv1_1024
  Results:
  - Dataset: FFHQ
    Metrics:
      FID50k: 4.056
      P&R50k_full: 70.302/36.869
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/styleganv1/styleganv1_ffhq_1024_g8_25Mimg_20210407_161627-850a7234.pth
