Collections:
- Metadata:
    Architecture: []
  Name: README
  Paper:
  - https://openaccess.thecvf.com/content_iccv_2017/html/Mao_Least_Squares_Generative_ICCV_2017_paper.html
  README: configs/lsgan/README.md
Models:
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/lsgan/lsgan_dcgan-archi_lr-1e-3_celeba-cropped_64_b128x1_12m.py
  In Collection: README
  Metadata:
    Training Data: CELEBA
  Name: lsgan_lr-1e-3
  Results:
  - Dataset: CELEBA
    Metrics:
      Dataset: CelebA-Cropped
      FID: 11.9258
      MS-SSIM: 0.3216
      Models: LSGAN 64x64
      SWD: 6.16, 6.83, 37.64/16.87
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/lsgan/lsgan_celeba-cropped_dcgan-archi_lr-1e-3_64_b128x1_12m_20210429_144001-92ca1d0d.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/lsgan/lsgan_dcgan-archi_lr-1e-4_lsun-bedroom_64_b128x1_12m.py
  In Collection: README
  Metadata:
    Training Data: LSUN
  Name: lsgan_dcgan-archi
  Results:
  - Dataset: LSUN
    Metrics:
      Dataset: LSUN-Bedroom
      FID: 30.739
      MS-SSIM: 0.0671
      Models: LSGAN 64x64
      SWD: 5.66, 9.0, 18.6/11.09
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/lsgan/lsgan_lsun-bedroom_dcgan-archi_lr-1e-4_64_b128x1_12m_20210429_144602-ec4ec6bb.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/lsgan/lsgan_dcgan-archi_lr-1e-4_celeba-cropped_128_b64x1_10m.py
  In Collection: README
  Metadata:
    Training Data: CELEBA
  Name: lsgan_lr-1e-4
  Results:
  - Dataset: CELEBA
    Metrics:
      Dataset: CelebA-Cropped
      FID: 38.3752
      MS-SSIM: 0.3691
      Models: LSGAN 128x128
      SWD: 21.66, 9.83, 16.06, 70.76/29.58
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/lsgan/lsgan_celeba-cropped_dcgan-archi_lr-1e-4_128_b64x1_10m_20210429_144229-01ba67dc.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/lsgan/lsgan_lsgan-archi_lr-1e-4_lsun-bedroom_128_b64x1_10m.py
  In Collection: README
  Metadata:
    Training Data: LSUN
  Name: lsgan_lsgan-archi
  Results:
  - Dataset: LSUN
    Metrics:
      Dataset: LSUN-Bedroom
      FID: 51.55
      MS-SSIM: 0.0612
      Models: LSGAN 128x128
      SWD: 19.52, 9.99, 7.48, 14.3/12.82
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/lsgan/lsgan_lsun-bedroom_lsgan-archi_lr-1e-4_128_b64x1_10m_20210429_155605-cf78c0a8.pth
