Collections:
- Metadata:
    Architecture:
    - StyleGANv3
  Name: StyleGANv3
  Paper:
  - https://nvlabs-fi-cdn.nvidia.com/stylegan3/stylegan3-paper.pdf
  README: configs/styleganv3/README.md
Models:
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/_base_/models/stylegan/stylegan3_t_ffhqu_256_b4x8_cvt_official_rgb.py
  In Collection: StyleGANv3
  Metadata:
    Training Data: FFHQ
  Name: stylegan3_t_ffhqu_256_b4x8_cvt_official_rgb
  Results:
  - Dataset: FFHQ
    Metrics:
      Comment: official weight
      EQ-R: 13.12
      EQ-T: 63.01
      FID50k: 4.62
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan3/stylegan3_t_ffhqu_256_b4x8_cvt_official_rgb_20220329_235046-153df4c8.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/_base_/models/stylegan/stylegan3_t_afhqv2_512_b4x8_cvt_official_rgb.py
  In Collection: StyleGANv3
  Metadata:
    Training Data: Others
  Name: stylegan3_t_afhqv2_512_b4x8_cvt_official_rgb
  Results:
  - Dataset: Others
    Metrics:
      Comment: official weight
      EQ-R: 13.51
      EQ-T: 60.15
      FID50k: 4.04
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan3/stylegan3_t_afhqv2_512_b4x8_cvt_official_rgb_20220329_235017-ee6b037a.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/_base_/models/stylegan/stylegan3_t_ffhq_1024_b4x8_cvt_official_rgb.py
  In Collection: StyleGANv3
  Metadata:
    Training Data: FFHQ
  Name: stylegan3_t_ffhq_1024_b4x8_cvt_official_rgb
  Results:
  - Dataset: FFHQ
    Metrics:
      Comment: official weight
      EQ-R: 13.82
      EQ-T: 61.21
      FID50k: 2.79
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan3/stylegan3_t_ffhq_1024_b4x8_cvt_official_rgb_20220329_235113-db6c6580.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/_base_/models/stylegan/stylegan3_r_ffhqu_256_b4x8_cvt_official_rgb.py
  In Collection: StyleGANv3
  Metadata:
    Training Data: FFHQ
  Name: stylegan3_r_ffhqu_256_b4x8_cvt_official_rgb
  Results:
  - Dataset: FFHQ
    Metrics:
      Comment: official weight
      EQ-R: 40.48
      EQ-T: 66.65
      FID50k: 4.5
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan3/stylegan3_r_ffhqu_256_b4x8_cvt_official_rgb_20220329_234909-4521d963.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/_base_/models/stylegan/stylegan3_r_afhqv2_512_b4x8_cvt_official_rgb.py
  In Collection: StyleGANv3
  Metadata:
    Training Data: Others
  Name: stylegan3_r_afhqv2_512_b4x8_cvt_official_rgb
  Results:
  - Dataset: Others
    Metrics:
      Comment: official weight
      EQ-R: 40.34
      EQ-T: 64.89
      FID50k: 4.4
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan3/stylegan3_r_afhqv2_512_b4x8_cvt_official_rgb_20220329_234829-f2eaca72.pth
- Config: https://github.com/open-mmlab/mmgeneration/tree/master/configs/_base_/models/stylegan/stylegan3_r_ffhq_1024_b4x8_cvt_official_rgb.py
  In Collection: StyleGANv3
  Metadata:
    Training Data: FFHQ
  Name: stylegan3_r_ffhq_1024_b4x8_cvt_official_rgb
  Results:
  - Dataset: FFHQ
    Metrics:
      Comment: official weight
      EQ-R: 46.62
      EQ-T: 64.76
      FID50k: 3.07
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmgen/stylegan3/stylegan3_r_ffhq_1024_b4x8_cvt_official_rgb_20220329_234933-ac0500a1.pth
